#version: "3.9"

secrets:
  mariadb-root-password:
    file: ./secrets/mariadb-root.txt
  mariadb-user-password:
    file: ./secrets/mariadb-user.txt
  mongo-root-password:
    file: ./secrets/mongo-root.txt
  rabbitmq-user-password:
    file: ./secrets/rabbitmq-user.txt
  rabbitmq-config:
    file: ./secrets/rabbitmq.conf
  wsapi-config:
    file: ./secrets/application.properties


services:
  sqldatabase:
    image: mariadb:11
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mariadb-root-password
      - MARIADB_DATABASE=myrames-prod-db
      - MARIADB_USER=mariaUsr
      - MARIADB_PASSWORD_FILE=/run/secrets/mariadb-user-password
    secrets:
      - mariadb-root-password
      - mariadb-user-password
    volumes:
      - sqldata:/var/lib/mysql
      - ./docker/sql/init:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s


  nosqldatabase:
    image: mongo:6.0
    environment:
      - MONGO_INITDB_DATABASE=HistoryDB
      - MONGO_INITDB_ROOT_USERNAME=mongoRoot
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo-root-password
    secrets:
      - mongo-root-password
    volumes:
      - mongodata:/data/db
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  broker:
    build:
      context: ./docker
      dockerfile: rabbitmq.Dockerfile
    environment:
      - RABBITMQ_CONFIG_FILE=/run/secrets/rabbitmq-config
    secrets:
        - rabbitmq-config
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  restapi:
    build:
      context: .
      dockerfile: ./docker/restapi.Dockerfile
    depends_on:
      sqldatabase:
        condition: service_healthy
      nosqldatabase:
        condition: service_healthy
    secrets:
      - mariadb-user-password
      - mongo-root-password
    restart: on-failure

  wsapi:
    image: maven:3-eclipse-temurin-21
    working_dir: /usr/src/app
    secrets:
      - mariadb-user-password
      - mongo-root-password
      - rabbitmq-user-password
      - wsapi-config
    volumes:
      - ./RealtimeAPI:/usr/src/app
      - maven-cache:/root/.m2
      - wsapi-target:/usr/src/app/target
      - type: bind
        source: ./secrets/application.properties
        target: /usr/src/app/src/main/resources/application.properties
        read_only: true
    command: ["mvn", "spring-boot:run"]
    depends_on:
      sqldatabase:
        condition: service_healthy
      nosqldatabase:
        condition: service_healthy
      broker:
        condition: service_healthy
    restart: on-failure

  webapp:
    image: node:22-alpine
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
      - webapp-build:/usr/src/app/build
    command: ["npm", "run", "build"]
    profiles: ["builder"]

  front:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      restapi:
        condition: service_started
      wsapi:
        condition: service_started
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -fso /dev/null http://127.0.0.1:80/health"]
      interval: 10s
      timeout : 10s
      retries: 10
      start_period: 60s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_USER=mariaUsr
      - PMA_HOST=sqldatabase
      - PMA_PASSWORD_FILE=/run/secrets/mariadb-user-password
    secrets:
      - mariadb-user-password
    ports:
      - "8081:80"
    profiles: ["dev-tool"]

  mongo-express:
    image: mongo-express
    env_file:
    - ./secrets/mongo-express.env
    ports:
      - "8082:8081"
    profiles: ["dev-tool"]

volumes:
  sqldata:
  mongodata:
  maven-cache:
  wsapi-target:
  webapp-build:
