version: "3.9"

services:
  sqldatabase:
    image: mariadb:11
    environment:
      - MARIADB_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MARIADB_DATABASE=myrames-prod-db
      - MARIADB_USER=mariaUsr
      - MARIADB_PASSWORD=mariaPwd
    volumes:
      - sqldata:/var/lib/mysql
      - ./docker/sql/init:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s


  nosqldatabase:
    image: mongo:6.0
    environment:
      - MONGO_INITDB_DATABASE=HistoryDB
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodata:/data/db
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  broker:
    image: rabbitmq:3.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  restapi:
    build:
      context: ./RESTApi
      dockerfile: ./docker/restapi.Dockerfile
    depends_on:
      - sqldatabase
      - nosqldatabase
    restart: on-failure

  wsapi:
    image: maven:3-eclipse-temurin-21
    working_dir: /usr/src/app
    volumes:
      - ./RealtimeAPI:/usr/src/app
      - maven-cache:/root/.m2
      - wsapi-target:/usr/src/app/target
    command: ["mvn", "spring-boot:run"]
    depends_on:
      - sqldatabase
      - nosqldatabase
      - broker
    restart: on-failure

  webapp:
    image: node:22-alpine
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
      - webapp-build:/usr/src/app/build
    command: ["npm", "run", "build"]
    profiles: ["builder"]

  front:
    build:
      context: ./vendorConfigurations
      dockerfile: ./nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - restapi
      - wsapi
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -fso /dev/null http://127.0.0.1:80/health"]
      interval: 10s
      timeout : 10s
      retries: 10
      start_period: 60s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=sqldatabase
    ports:
      - "8081:80"
    profiles: ["dev-tool"]

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=nosqldatabase
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
    ports:
      - "8082:8081"
    profiles: ["dev-tool"]

volumes:
  sqldata:
  mongodata:
  maven-cache:
  wsapi-target:
  webapp-build:
